# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: Copyright © 2024 Free Software Foundation Europe e.V.

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
